// Auto-generated by Supabase. Do not edit by hand.
// Regenerate with the Supabase MCP `generate_typescript_types` tool, or
//   supabase gen types typescript --project-id qiowxcaofwjahlwycwbl > types/database.ts
//
// Used by /lib/supabase/{client,server}.ts as the Database generic on createClient.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      activity: {
        Row: {
          broker_id: string
          created_at: string
          id: string
          meta: Json | null
          module_id: string | null
          project_id: string | null
          type: string
        }
        Insert: {
          broker_id: string
          created_at?: string
          id?: string
          meta?: Json | null
          module_id?: string | null
          project_id?: string | null
          type: string
        }
        Update: {
          broker_id?: string
          created_at?: string
          id?: string
          meta?: Json | null
          module_id?: string | null
          project_id?: string | null
          type?: string
        }
        Relationships: [
          {
            foreignKeyName: "activity_broker_id_fkey"
            columns: ["broker_id"]
            isOneToOne: false
            referencedRelation: "brokers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "activity_module_id_fkey"
            columns: ["module_id"]
            isOneToOne: false
            referencedRelation: "modules"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "activity_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
      ai_config: {
        Row: {
          id: string
          instructions: string
          max_output_tokens: number
          model: string
          temperature: number
          updated_at: string
        }
        Insert: {
          id: string
          instructions: string
          max_output_tokens?: number
          model?: string
          temperature?: number
          updated_at?: string
        }
        Update: {
          id?: string
          instructions?: string
          max_output_tokens?: number
          model?: string
          temperature?: number
          updated_at?: string
        }
        Relationships: []
      }
      ai_sources: {
        Row: {
          content: string | null
          created_at: string
          enabled: boolean
          file_url: string | null
          id: string
          kind: string
          project_id: string | null
          sort_order: number
          title: string
          updated_at: string
        }
        Insert: {
          content?: string | null
          created_at?: string
          enabled?: boolean
          file_url?: string | null
          id?: string
          kind?: string
          project_id?: string | null
          sort_order?: number
          title: string
          updated_at?: string
        }
        Update: {
          content?: string | null
          created_at?: string
          enabled?: boolean
          file_url?: string | null
          id?: string
          kind?: string
          project_id?: string | null
          sort_order?: number
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "ai_sources_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
      brokers: {
        Row: {
          brokerage: string | null
          created_at: string
          engagement_score: number
          id: string
          name: string
          photo_url: string | null
          points: number
          role: string | null
          tier: string
          user_id: string | null
        }
        Insert: {
          brokerage?: string | null
          created_at?: string
          engagement_score?: number
          id: string
          name: string
          photo_url?: string | null
          points?: number
          role?: string | null
          tier?: string
          user_id?: string | null
        }
        Update: {
          brokerage?: string | null
          created_at?: string
          engagement_score?: number
          id?: string
          name?: string
          photo_url?: string | null
          points?: number
          role?: string | null
          tier?: string
          user_id?: string | null
        }
        Relationships: []
      }
      campaigns: {
        Row: {
          created_at: string
          id: string
          image: string | null
          kind: string | null
          link_target: string | null
          published: boolean
          schedule: string | null
          subtitle: string | null
          tag: string | null
          title: string
        }
        Insert: {
          created_at?: string
          id: string
          image?: string | null
          kind?: string | null
          link_target?: string | null
          published?: boolean
          schedule?: string | null
          subtitle?: string | null
          tag?: string | null
          title: string
        }
        Update: {
          created_at?: string
          id?: string
          image?: string | null
          kind?: string | null
          link_target?: string | null
          published?: boolean
          schedule?: string | null
          subtitle?: string | null
          tag?: string | null
          title?: string
        }
        Relationships: []
      }
      modules: {
        Row: {
          created_at: string
          duration: string | null
          id: string
          kind: string
          location: string | null
          points: number
          project_id: string | null
          published: boolean
          quiz: Json | null
          seats: string | null
          tier_required: string | null
          title: string
          when_at: string | null
        }
        Insert: {
          created_at?: string
          duration?: string | null
          id: string
          kind: string
          location?: string | null
          points?: number
          project_id?: string | null
          published?: boolean
          quiz?: Json | null
          seats?: string | null
          tier_required?: string | null
          title: string
          when_at?: string | null
        }
        Update: {
          created_at?: string
          duration?: string | null
          id?: string
          kind?: string
          location?: string | null
          points?: number
          project_id?: string | null
          published?: boolean
          quiz?: Json | null
          seats?: string | null
          tier_required?: string | null
          title?: string
          when_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "modules_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
      notifications: {
        Row: {
          audience: string | null
          body: string | null
          created_at: string
          id: string
          link_target: string | null
          sent: boolean
          sent_at: string | null
          title: string
        }
        Insert: {
          audience?: string | null
          body?: string | null
          created_at?: string
          id: string
          link_target?: string | null
          sent?: boolean
          sent_at?: string | null
          title: string
        }
        Update: {
          audience?: string | null
          body?: string | null
          created_at?: string
          id?: string
          link_target?: string | null
          sent?: boolean
          sent_at?: string | null
          title?: string
        }
        Relationships: []
      }
      projects: {
        Row: {
          ai_indexed: boolean
          brochure_url: string | null
          cover_image: string | null
          created_at: string
          facts: Json | null
          featured: boolean
          id: string
          location: string | null
          name: string
          price_from: string | null
          published: boolean
          status: string | null
          tagline: string | null
          units: string | null
          video_url: string | null
        }
        Insert: {
          ai_indexed?: boolean
          brochure_url?: string | null
          cover_image?: string | null
          created_at?: string
          facts?: Json | null
          featured?: boolean
          id: string
          location?: string | null
          name: string
          price_from?: string | null
          published?: boolean
          status?: string | null
          tagline?: string | null
          units?: string | null
          video_url?: string | null
        }
        Update: {
          ai_indexed?: boolean
          brochure_url?: string | null
          cover_image?: string | null
          created_at?: string
          facts?: Json | null
          featured?: boolean
          id?: string
          location?: string | null
          name?: string
          price_from?: string | null
          published?: boolean
          status?: string | null
          tagline?: string | null
          units?: string | null
          video_url?: string | null
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
